# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

pre_install do |installer|
  # Workaround for Boost download host returning wrong/corrupt archive
  # Prefer local cached Boost tarball, else replace JFrog URL with official archives mirror
  boost_podspec = File.join(__dir__, '../node_modules/react-native/third-party-podspecs/boost.podspec')
  if File.exist?(boost_podspec)
    contents = File.read(boost_podspec)
    local_boost = File.expand_path('boost_temp/boost_1_76_0.tar.bz2', __dir__)
    target_url = if File.exist?(local_boost)
      "file://#{local_boost}"
    else
      'https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2'
    end
    # Replace the entire source line, removing checksum verification
    fixed = contents
      .gsub(/spec\.source = \{ :http => '[^']*',\s*:sha256 => '[^']*' \}/m, 
            "spec.source = { :http => '#{target_url}' }")
      .gsub(/spec\.source = \{ :http => '[^']*'\}/m, 
            "spec.source = { :http => '#{target_url}' }")
    if fixed != contents
      File.open(boost_podspec, 'w') { |f| f.write(fixed) }
    end
  end
end

target 'BirchwoodStudent' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Force-disable Hermes to avoid TestFlight bitcode rejection in hermes.framework
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'BirchwoodStudentTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
    
  end
end
