const routes = {
  navigator: {
    mainTabs: 'MainTabs',
    onboard: 'OnBoard',
    signin: 'SignIn',
    signup: 'SignUP',
    passwordresetscreens: 'PasswordResetScreens',
    personalInfo: 'PersonalInfo',
    education: 'Education',
    parentContact: 'ParentContact',
    experience: 'Experience',
  },
  screens: {
    homeScreen: 'HomeScreen',
    profile: 'Profile',
    addChild: 'AddChild',
    childProfile: 'ChildProfile',
    healthDetails: 'HealthDetails',
    profileForm: 'ProfileForm',
    attendanceLog: 'AttendanceLog',
    feesDue: 'FeesDue',
    timeTable: 'TimeTable',
    schoolAlbums: 'SchoolAlbums',
    result: 'Result',
    checkIn: 'CheckIn',
    leaveApplication: 'LeaveApplication',
    activityScreen: 'ActivityScreen',
    activityDetail: 'ActivityDetail',
    emptyDashboard: 'EmptyDashboard',
    settings: 'Settings',
    children: 'Children',
    schoolCalendar: 'SchoolCalendar',
    diaryHomework: 'DiaryHomework',
    notices: 'Notices',
    notifications: 'Notifications',
    helpSupport: 'HelpSupport',
    changePassword: 'ChangePassword',
  },
};

export default routes;
