import {StyleSheet} from 'react-native';
import fonts from '../../Assets/fonts';

const NAVY = '#0F1F4B';
const MUTED = '#8B93A7';
const PAGE = '#F4F5F8';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: PAGE,
  },
  flex: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingLeft: 8,
    paddingRight: 18,
    paddingBottom: 12,
  },
  switcher: {
    marginLeft: 12,
  },
  backBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
    paddingBottom: 2,
  },
  eyebrow: {
    fontFamily: fonts.euclidCircularA.medium,
    fontSize: 13,
    color: MUTED,
  },
  headerTitle: {
    marginTop: 2,
    fontFamily: fonts.euclidCircularA.semiBold,
    fontSize: 32,
    letterSpacing: -0.6,
    color: '#035392',
  },
  tabs: {
    flexDirection: 'row',
    gap: 8,
    marginHorizontal: 18,
    marginBottom: 12,
  },
  tab: {
    flex: 1,
    height: 38,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabOn: {
    backgroundColor: '#035392',
  },
  tabText: {
    fontFamily: fonts.euclidCircularA.medium,
    fontSize: 14,
    color: NAVY,
  },
  tabTextOn: {
    color: '#FFFFFF',
  },
  scroll: {
    paddingHorizontal: 18,
    paddingTop: 2,
    paddingBottom: 36,
  },
  hero: {
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 18,
    marginBottom: 12,
  },
  heroKicker: {
    fontFamily: fonts.euclidCircularA.medium,
    fontSize: 13,
    color: '#D6E6F5',
  },
  heroTitle: {
    marginTop: 4,
    fontFamily: fonts.euclidCircularA.semiBold,
    fontSize: 22,
    letterSpacing: -0.4,
    color: '#FFFFFF',
  },
  heroMeta: {
    marginTop: 6,
    fontFamily: fonts.euclidCircularA.medium,
    fontSize: 14,
    color: '#FFFFFF',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    paddingHorizontal: 12,
    paddingTop: 14,
    paddingBottom: 8,
    marginBottom: 12,
  },
  kicker: {
    paddingHorizontal: 6,
    fontFamily: fonts.euclidCircularA.semiBold,
    fontSize: 11,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: MUTED,
  },
  monthTitle: {
    fontFamily: fonts.euclidCircularA.semiBold,
    fontSize: 16,
    color: NAVY,
  },
  dayText: {
    fontFamily: fonts.euclidCircularA.medium,
    fontSize: 14,
    color: NAVY,
  },
  todayText: {
    color: '#035392',
    fontFamily: fonts.euclidCircularA.semiBold,
  },
  rangeDay: {
    backgroundColor: '#B7D4EE',
  },
  chips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 6,
    paddingTop: 12,
  },
  chip: {
    height: 34,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: '#E7F1FA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipOn: {
    backgroundColor: '#035392',
  },
  chipText: {
    fontFamily: fonts.euclidCircularA.medium,
    fontSize: 13,
    color: '#035392',
  },
  chipTextOn: {
    color: '#FFFFFF',
  },
  note: {
    marginTop: 12,
    marginHorizontal: 6,
    marginBottom: 8,
    minHeight: 88,
    borderRadius: 16,
    backgroundColor: '#F4F5F8',
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 12,
    textAlignVertical: 'top',
    fontFamily: fonts.euclidCircularA.regular,
    fontSize: 15,
    color: NAVY,
  },
  submit: {
    height: 52,
    borderRadius: 16,
    backgroundColor: '#035392',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 22,
  },
  submitText: {
    fontFamily: fonts.euclidCircularA.semiBold,
    fontSize: 16,
    color: '#FFFFFF',
  },
  loader: {
    marginTop: 28,
  },
  emptyCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  emptyIcon: {
    width: 58,
    height: 58,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#035392',
  },
  emptyCopy: {
    flex: 1,
    minWidth: 0,
    paddingTop: 4,
  },
  emptyTitle: {
    fontFamily: fonts.euclidCircularA.semiBold,
    fontSize: 16,
    letterSpacing: -0.2,
    color: NAVY,
  },
  emptyBody: {
    marginTop: 4,
    fontFamily: fonts.euclidCircularA.regular,
    fontSize: 13,
    lineHeight: 18,
    color: MUTED,
  },
  historyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    marginBottom: 12,
    overflow: 'hidden',
  },
  historyRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  dateBox: {
    width: 58,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: '#035392',
  },
  dateDay: {
    fontFamily: fonts.euclidCircularA.semiBold,
    fontSize: 22,
    letterSpacing: -0.4,
    color: '#FFFFFF',
  },
  dateMonth: {
    marginTop: -2,
    fontFamily: fonts.euclidCircularA.medium,
    fontSize: 12,
    textTransform: 'uppercase',
    color: '#FFFFFF',
  },
  historyBody: {
    flex: 1,
    minWidth: 0,
  },
  historyKicker: {
    fontFamily: fonts.euclidCircularA.semiBold,
    fontSize: 11,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: '#035392',
  },
  historyTitle: {
    marginTop: 4,
    fontFamily: fonts.euclidCircularA.semiBold,
    fontSize: 16,
    letterSpacing: -0.2,
    color: NAVY,
  },
  historyWhen: {
    marginTop: 4,
    fontFamily: fonts.euclidCircularA.semiBold,
    fontSize: 13,
    color: NAVY,
  },
  historyNote: {
    marginTop: 6,
    fontFamily: fonts.euclidCircularA.regular,
    fontSize: 13,
    lineHeight: 18,
    color: '#3E4658',
  },
});
